1. What is a "feature"?<br>
    Unique transformation of data that can be helped to model data. Like edge detection will detect all the edges in the convolution early layers. 
1. Write out the convolutional kernel matrix for a top edge detector.<br>
    \begin{bmatrix} -1 & -1 & -1\\ 0 & 0 & 0 \\ 1 & 1 & 1 \end{bmatrix}
1. Write out the mathematical operation applied by a 3×3 kernel to a single pixel in an image.<br>
    Considering there is padding of size `1`. The pixel at (I, J) will be multiplied with all element of kernel.
1. What is the value of a convolutional kernel apply to a 3×3 matrix of zeros?<br>
    0's matrix
1. What is "padding"?<br>
    stacking dummy pixels(i.e 0) of size `ks//2` around the image.
1. What is "stride"?<br>
    jumping the kernel window in a image during consecutive convolution
1. Create a nested list comprehension to complete any task that you choose.<br>
    ```
    >>> [[10 * i + j for j in range(10)] for i in range(2)]
    [[0, 1, 2, 3, 4, 5, 6, 7, 8, 9], [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]]
    ```
1. What are the shapes of the `input` and `weight` parameters to PyTorch's 2D convolution?<br>
    input : batch_size * in_channel * height * width <br>
    weight : out_channel * in_channel * ks_height * ks_width
1. What is a "channel"? <br>
    data along specific dimensions. by combining all the channels data the original data is constructed. For 2d image channel is 1 for 3d it is 3.
1. What is the relationship between a convolution and a matrix multiplication? <br>
    to implement convolution via mat mult the weight matrix should be containing many `0` along with shared kernel.
1. What is a "convolutional neural network"? <br>
    use convolution to create initial NN insead
1. What is the benefit of refactoring parts of your neural network definition?<br>
    it much less likely you'll get errors due to inconsistencies in your architectures, and makes it more obvious to the reader which parts of your layers are actually changing.
1. What is `Flatten`? Where does it need to be included in the MNIST CNN? Why?<br>
    it removes the a given dimension if the end_dim is provided if nothing is given makes the tensor one dim.<br>
    the last conv layer give the output to 1*1, to 1 dimensional to match the label
1. What does "NCHW" mean?<br>
    batch size * in_channel * height * width
1. Why does the third layer of the MNIST CNN have `7*7*(1168-16)` multiplications?<br>
    1168 params 16 bias and the operation is done with 7 * 7 grid
1. What is a "receptive field"?<br>
    The receptive field is the area of an image that is involved in the calculation of a layer
1. What is the size of the receptive field of an activation after two stride 2 convolutions? Why?<br>
    7 * 7, more deeper the layer the receptive area increases
1. Run *conv-example.xlsx* yourself and experiment with *trace precedents*.

1. Have a look at Jeremy or Sylvain's list of recent Twitter "like"s, and see if you find any interesting resources or ideas there.
1. How is a color image represented as a tensor?<br>
    3 * height * width
1. How does a convolution work with a color input? <br>
    conv across each channel adn sum at the result
1. What method can we use to see that data in `DataLoaders`?<br>
    dls.show_batch()
1. Why do we double the number of filters after each stride-2 conv?<br>
    the size of image decrese by 4. so we double the sifilter to learn higher no of features
1. Why do we use a larger kernel in the first conv with MNIST (with `simple_cnn`)?<br>
    to force the NN to learn as we deviding the input size by 4
1. What information does `ActivationStats` save for each layer?<br>
    record mean, std deviation, and actiavation of each layer
1. How can we access a learner's callback after training?<br>
    `learn.activation_stats.plot_layer_stats(-2)`
1. What are the three statistics plotted by `plot_layer_stats`? What does the x-axis represent?<br>
    mean, std, %near 0. batch size in x-axis
1. Why are activations near zero problematic?<br>
    the network did not contribute to learning
1. What are the upsides and downsides of training with a larger batch size?<br>
    adv : it summerizes the training data well(ie act as normilization)<br>
    disadv : the memory rquired to train is very high
1. Why should we avoid using a high learning rate at the start of training?<br>
    the initial loss might be worse, if we act upon it and do step in gradient decent will worsen the params
1. What is 1cycle training?<br>
    combines learning rate warmup and annealing, which allows us to train with higher learning rates. 
1. What are the benefits of training with a high learning rate?<br>
    we can jump over local minima and reach the final/optimal solution faster(super convergence)
1. Why do we want to use a low learning rate at the end of training?<br>
    to find the sweet spot of the loss function
1. What is "cyclical momentum"?<br>
    higher the learning rate lower the momentum and vice versa in lower learning rate 
1. What callback tracks hyperparameter values during training (along with other information)?<br>
    `learn.recorder`
1. What does one column of pixels in the `color_dim` plot represent?
1. What does "bad training" look like in `color_dim`? Why?
1. What trainable parameters does a batch normalization layer contain?
1. What statistics are used to normalize in batch normalization during training? How about during validation?<br>
    during training it user running mean and variance for each feature.
    at validation we just have to use the learned parms in training
1. Why do models with batch normalization layers generalize better?<br>
    more random-ness to network and make the NN out less flactuate on the input

In [ ]:
[[10 * i + j for j in range(10)] for i in range(2)]

[[0, 1, 2, 3, 4, 5, 6, 7, 8, 9], [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]]

In [ ]:
import torch

A = torch.randn(4, 4)  # Shape: (3, 4)
B = torch.randn(3,3)  # Shape: (4, 5)

B


tensor([[-0.4344,  1.5026, -1.1545],
        [-0.2937,  0.4527, -0.2541],
        [ 0.0553, -1.5838,  1.3602]])

In [ ]:
C = (A[0:3,0:3] @ B).sum()
C

tensor(0.3183)

In [ ]:
A

tensor([[-1.4940, -0.7583,  1.0259, -1.8349],
        [-1.1792,  0.4408, -0.2068, -1.0183],
        [ 0.1546, -0.6246, -0.8864,  0.2593],
        [ 1.5381, -2.1038, -2.1639,  1.5233]])

In [ ]:
rng = range(1,3)
torch.tensor([[(A[i-1:i+2,j-1:j+2]*B).sum() for j in rng] for i in rng])

tensor([[-1.2843,  5.7471],
        [ 1.7842,  5.7728]])

In [ ]:
[[A[i-1:i+2,j-1:j+2] for j in rng] for i in rng]

[[tensor([[-1.4940, -0.7583,  1.0259],
          [-1.1792,  0.4408, -0.2068],
          [ 0.1546, -0.6246, -0.8864]]),
  tensor([[-0.7583,  1.0259, -1.8349],
          [ 0.4408, -0.2068, -1.0183],
          [-0.6246, -0.8864,  0.2593]])],
 [tensor([[-1.1792,  0.4408, -0.2068],
          [ 0.1546, -0.6246, -0.8864],
          [ 1.5381, -2.1038, -2.1639]]),
  tensor([[ 0.4408, -0.2068, -1.0183],
          [-0.6246, -0.8864,  0.2593],
          [-2.1038, -2.1639,  1.5233]])]]